theme: jekyll-theme-minimal
title: Agustin Forero's Personal Page
description: I am a passionate software developer with professional experience working with HPC systems, parallel programming, compiler testing and computational science. 
logo: pfp.jpg
stolaf: stolaf.png
cornell: cornell.png
