theme: jekyll-theme-minimal
title: Agustin Forero's Github Page
description: I am a passionate software developer with professional experience working with HPC systems, parallel programming, compiler testing and scientific collaboration. I have a great appreciation for the creation of patterns, the efficiency of algorithms and the conciseness of operations. I hope to one day create software that is widely applicable, easily understood, and readily adaptable.
logo: pfp.jpg
