theme: jekyll-theme-minimal
title: Agustin Forero's Personal Page
description: I am a passionate software developer with professional experience working with computational science, compiler testing, HPC systems and teaching. 
logo: pfp.jpg
stolaf: stolaf.gif
cornell: cornell.png
