theme: jekyll-theme-minimal
title: Agustin Forero's Github Page
description: I am a passionate software developer with professional experience working with HPC systems, parallel programming, compiler testing and scientific collaboration. I have a great appreciation for the efficiency of algorithms, the conciseness of operations and the ability to communicate ideas. I hope to one day create software that is widely applicable, easily understood, and readily adaptable. 
logo: pfp.jpg
