theme: jekyll-theme-minimal
title: Agustin Forero's Github Page
description: I am a passionate software developer with professional experience working with HPC systems, parallel programming, compiler testing and scientific collaboration. 
logo: pfp.jpg
