theme: jekyll-theme-minimal
title: Agustin Forero's Personal Page
description: I am a Cornell-educated software developer with a passion for programming, history and teaching. 
logo: pfp.jpg
stolaf: stolaf.png
cornell: cornell.png
